# Site settings
title: Integration of Artificial Intelligence in Robotic Applications
description: 'Blog Post'
url: 'https://acevedo88.github.io/jekyll-uno/'
baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Alex Acevedo'
  email: alexacevedo@u.boisestate.edu
  twitter_username: 
  facebook_username: 
  github_username:  
  linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
